// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBazkDPDtame3Wkn_aYKBvfAqXtiZZspA',
    appId: '1:470116158267:web:5f709fbc1a03ae55cbc51e',
    messagingSenderId: '470116158267',
    projectId: 'kat-chat-a3556',
    authDomain: 'kat-chat-a3556.firebaseapp.com',
    storageBucket: 'kat-chat-a3556.appspot.com',
    measurementId: 'G-H7NS7E6LVG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmz4jl6u_IXlqIhde09Qo3J2kRp3ywN1o',
    appId: '1:470116158267:android:2d6c60b778739912cbc51e',
    messagingSenderId: '470116158267',
    projectId: 'kat-chat-a3556',
    storageBucket: 'kat-chat-a3556.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvHrlmMUDZPAErGwL2fPbXRNXaOi0uW4k',
    appId: '1:470116158267:ios:2542f4483ce78f90cbc51e',
    messagingSenderId: '470116158267',
    projectId: 'kat-chat-a3556',
    storageBucket: 'kat-chat-a3556.appspot.com',
    iosBundleId: 'com.example.katChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvHrlmMUDZPAErGwL2fPbXRNXaOi0uW4k',
    appId: '1:470116158267:ios:417910336558075ccbc51e',
    messagingSenderId: '470116158267',
    projectId: 'kat-chat-a3556',
    storageBucket: 'kat-chat-a3556.appspot.com',
    iosBundleId: 'com.example.katChat.RunnerTests',
  );
}
